### ISSUE TITLE
Feature request: plot type Candlestick

### ISSUE THREAD

**Issue by durdn** [brentp/nim-plotly#13]
Hey there,

I'd love to use nim-plotly to draw Candlestick charts: https://plot.ly/python/candlestick-charts/

Please let me know if this is something that could be easily implemented. Otherwise I may try to hack something working and send over a PR. I see I can easily extend the plot types but the Candlestick has a slightly different set of inputs I need to understand how to pass in.

Cheers,
    Nicola

**Comment by brentp** [comment]
Hi, I looked at candlestick and they are one of the more complex. 
You can do this by: 
1. adding `Candlestick` to the [PlotTypes enum](https://github.com/brentp/nim-plotly/blob/master/src/plotly/plotly_types.nim#L6)

2. add the required attributes to the `Trace` object [here](https://plot.ly/javascript/candlestick-charts/)

3. updating the unfortunately long `%` proc for `Trace` [here](https://github.com/brentp/nim-plotly/blob/master/src/plotly/api.nim#L103)

4. add an example to examples/

**Comment by durdn** [comment]
Hey Brent!

I really appreciate your fast reply. Thanks for the guideline, I'll see if I can get it to work.

**Comment by brentp** [comment]
No problem. I would follow the javascript docs here: https://plot.ly/javascript/candlestick-charts/
since that's what nim-plotly is directly using.

Looks like you'll need to add at least `close`, `high`, `low`, `open` all of type `seq[T]` to the `Trace`

**Comment by durdn** [comment]
Alright thanks again I'll be looking into it the coming days.

**Comment by brentp** [comment]
closed by #14
