### ISSUE TITLE
support webview

### ISSUE THREAD

**Issue by brentp** [brentp/nim-plotly#31]
see e.g.: https://github.com/numforge/monocle/blob/master/src/monocle/viz.nim from @mratsim
that uses https://github.com/oskca/webview

this could be either via `when defined(webview)` or another mechanism currently unknown to me.

**Comment by Vindaar** [comment]
Heh, good thing you add this as an issue. After I saw @mratsim using webview in monocle, I played around with it in plotly. Hacked it in and it works well.

I'll try to implement that cleanly soon and create a PR.
