### ISSUE TITLE
plotly breaks nim CI

### ISSUE THREAD

**Issue by timotheecour** [brentp/nim-plotly#67]
refs https://github.com/nim-lang/Nim/issues/16419

**Comment by timotheecour** [comment]
@brentp out of curiosity how come did nim-plotly's CI did not catch this before the merge?

**Comment by brentp** [comment]
travis-ci no longer works for free projects. https://news.ycombinator.com/item?id=25338983

(is that what you mean?)

**Comment by xflywind** [comment]
Last CI run at 17 Oct, then I'm guess that [chroma](https://github.com/treeform/chroma) doesn't have breaking changes.

**Comment by Vindaar** [comment]
> then I guess that chroma didn't have breaking changes then.

`chroma` *did* have a breaking change! 
https://github.com/treeform/chroma/commit/91f76f6782549b3a804f18d3b36cc108719986df

Which tbf is partly my fault, cause I didn't get into looking into the performance regression in `chroma`.
