### ISSUE TITLE
data is already plural :-)

### ISSUE THREAD

**Issue by andreaferretti** [brentp/nim-plotly#8]
Silly, I know, but still it should be `Plot(data: ...)`, not `Plot(datas: ...)`. The singular of data is datum.

I know it is not especially important, but it is a detail that makes a bad first impression

**Comment by brentp** [comment]
duly noted. I'm on it.

**Comment by brentp** [comment]
I changed `datas` to `traces` which is more descriptive anyway. Thanks for reporting.
